#!/usr/bin/env ruby

rreqdir=File.expand_path(File.dirname(__FILE__))
$:.unshift(rreqdir) unless $:.include?(rreqdir)

require 'giddy'

giddy=Giddy.new(ARGV)

action=giddy.options[:action]

case action
when :INIT
	$log.debug "Initializing giddy"
	giddy.config.init
when :LIST
	giddy.list
when :BACKUP
	giddy.backup
when :UPDATE
	giddy.update
when :DELETE
	giddy.delete
else
	$log.die "Unknown action"
end

